databases:
  - name: postgres
    ipAllowList: []
    databaseName: todo_api_production
    user: portgres

services:
  - type: web
    name: todo_api_production
    env: ruby
    buildCommand: ./render-build.sh
    startCommand: bundle exec rails s -p 3000 -b 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled
      - key: RAILS_MASTER_KEY
        sync: false # Manually add it in Render dashboard (from config/master.key)
